#!/bin/bash

BASE=$(cd $(dirname "$0") && pwd)

for src in $(cd "$BASE" && find "." -type f -not -path "*/.git/*" | grep -v "initialize-dotfiles"); do

    # Destination
    dir=$(dirname "$src")
    if [[ "$dir" == "." ]]; then dst=".$(basename "$src")";
    else dst=".${dir:2}/$(basename "$src")"; fi
    dst="$HOME/$dst";
    src="$BASE/${src:2}";

    # Overwrite?
    mkdir -p "$(dirname "$dst")"
    if [ -e "$dst" ]; then
        echo -n "Overwrite '$dst'? [y/n] " 1>&2;
        read line
        case "$line" in
            "y")
                rm "$dst";
                ;;
            "q")
                break;;
            *)
                continue;;
        esac
    fi

    # Link it!
    echo -n "$src -> $dst ..."
    ln -s "$src" "$dst"
    if [[ "$?" == "0" ]]; then
        echo "OK."
    else
        exit 1;
    fi
done
